spring:
  datasource:
    url: jdbc:mysql://ycsin.cn:3306/activiti?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: PassW0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  activiti:
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: true
    #配置项可以设置流程引擎启动和关闭时数据库执行的策略
    database-schema-update: true
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full