server:
  port: 8080

spring:
  application:
    name: provider-demo

eureka:
  instance:
    instance-id: provider-demo-01
    appname: provider-demo

  client:
    service-url:
      defaultZone: http://localhost:9876/eureka/